### ISSUE TITLE
0 db számlát jelez a rendszerben

### ISSUE THREAD

**Issue by adamkovacs2000** [juzraai/dijnet-bot#32]
**Mi történt? Mit tapasztaltál?**
0 db számlát jelez a rendszerben

**Milyen szituációban? Hogyan futtattad a programot? Hogyan tudom reprodukálni a hibát?**
normál futtatás

**Mi lenne az elvárt működés? Minek kellett volna történnie?**
...

**error.log fájl tartalma**
nincs

**Rendszerinformáció**
 - Operációs rendszer: Windows
 - Node verzió: 
 - Program verzió: ?
<img width="396" alt="Screenshot 2022-12-06 205133" src="https://user-images.githubusercontent.com/67317361/206009039-bbe99e20-dc45-4157-bbf3-6ee8eec37fb2.png">

**Comment by juzraai** [comment]
@alphadam2000 Köszi a jelzést! A hibát sikerült reprodukálni. Ránézésre változott a DíjNet honlap, után kell igazítanom a kódot. Igyekszem hamarosan (pár nap) megcsinálni.

**Comment by juzraai** [comment]
@alphadam2000 Javítottam a hibát az új [v2.1.8-as verzióban](https://github.com/juzraai/dijnet-bot/releases/tag/v2.1.8).
