### ISSUE TITLE
0 számla találat, pedig van

### ISSUE THREAD

**Issue by ponyitomi** [juzraai/dijnet-bot#35]
**Mi történt? Mit tapasztaltál?**
Release 3.0.1-et használtam.
A program teljesen jól működik (nincs hiba) csak a dijnet-ről 0 számlát talált nekem, holott van vagy 123 db.
A POST kérésre a dijnet (.../ekonto/control/szamla_search_submit) a válasz ...html csak a form adatokat küldi.

**Milyen szituációban? Hogyan futtattad a programot? Hogyan tudom reprodukálni a hibát?**
Bárhol, nem ismeri fel a számlákat.

**Mi lenne az elvárt működés? Minek kellett volna történnie?**
Minden számlát megtalál. De a POST-al lekért válasz html nem tartalmazza a táblázatot és adatot, ezért nem találja a táblázatot és adatokat.

**error.log fájl tartalma**

nincs
Ide másold be kérlek.
nincs

**(Ha nincs error.log fájl) Rendszerinformációk**

-   Operációs rendszer: Windows? Linux? Linux Kubuntu 23.10
-   Node verzió (`node -v`): ? Node 19.9
-   Program verzió: ? 3.0.1 (Release-ből szedve)

Megoldás:
A POST kérést lecseréltem GET-re és így a dijnet a teljes számlaösszesítő táblázattal feltöltött html fájlt adja válaszul.

tehát, ha a dijnet-agent.js fájlban ez szerepel **await.this.browser.submit** helyett **await.this.browser.navigate**, akkor gyönyörűen megy a progi, megtalálja és tölti a számlákat (POST helyett, GET kérés). A GET-re a teljes .html válasz jön a táblázattal és adatokkal.

a helyes kód dijnet-agent.js :
...
/**
* Submits bill search form.
 */
    async submitBillSearchForm() {
		this.checkIfLoggedIn();
		this.checkBillSearchForm();
		const body =
			'vfw_form=szamla_search_submit&vfw_coll=szamla_search_params&regszolgid=&szlaszolgid=&datumtol=&datumig=';
		await this.browser.**navigate**('/control/szamla_search_submit', body); // try with get/instead of post/submit
	}
....

Nagyon köszi! Szuper program, már a bash progit is használtam korábban. Óriási segítség, szép progi! Gratula!

**Comment by juzraai** [comment]
Köszi a hibajelzést, az ajánlott javítást és a pozitív visszajelzést is! :) Az ajánlott javítás valóban működik, és egyszerűen megkerüli a form küldés problémáját.

Végül nem ezt alkalmaztam, hanem sikerült megbütykölnöm a POST-ot, egy hidden paraméter hiányzott. Így továbbra is reális request-eket küldünk.

[v3.0.2](https://github.com/juzraai/dijnet-bot/releases/tag/v3.0.2)-ben kint van a javítás.

**Comment by ponyitomi** [comment]
Én köszi! Szuper megoldás! Keep up the good work!
