### ISSUE TITLE
93/103 - Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Merwenus** [juzraai/dijnet-bot#8]
**Mi történt? Mit tapasztaltál?**
...103ból 93-at lementett, aztán hibára fut, ki-be lépés nem segít. Elölről kezdtem az egészet törölve az előző letöltéseket, hátha egyedi hiba, de ugyanott akadt meg:
```
93/103 db új számla lementve (90%) | 2018.08.27 JOVAIRAS | [1/4] Szamla nyomtathato verzioja PDF - Hiteles szamla
Cannot read property 'replace' of undefined

Ha biztos vagy abban, hogy helyesen konfiguráltad a Díjnet Bot-ot, akkor a hiba a programban lehet.
Kérlek, az alábbi linken nyiss egy új issue-t, másold be a hiba részleteit, és írd le röviden, milyen szituációban jelentkezett a hiba!

-->  https://github.com/juzraai/dijnet-bot/issues
```

**Milyen szituációban? Hogyan futtattad a programot? Hogyan tudom reprodukálni a hibát?**
...Synology, Node v8 és v12 telepítve, az oldlon szereplő `node dijnet-bot` paranccsal, mindenféle változtatás, és változó nélkül a legfrissebb letöltött fájllal.

**Mi lenne az elvárt működés? Minek kellett volna történnie?**
...103/103 letöltés, és hiba nélkül lefutás.

**error.log fájl tartalma**
```
2020-06-01 5:44:45 PM: Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at t.exports.download (/volume3/Downloads/Dijnet/dijnet-bot.js:204:9770)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async start (/volume3/Downloads/Dijnet/dijnet-bot.js:204:14443)
```

**Rendszerinformáció**
 - Operációs rendszer: Synology DSM 6.2.2
 - Node verzió: V8 és V12, nem tudom melyiket használja
 - Program verzió: v2.1.5

**Comment by juzraai** [comment]
Szia, köszi, igyekszem javítani. :) Meg tudnád nézni kérlek, hogy ha a Díjnet felületén rámész erre a számládra (2018.08.27, JOVAIRAS), és rákattintasz a "Szamla nyomtathato verzioja PDF - Hiteles szamla" linkre, akkor mi történik? A böngésződ letölti a PDF-et? Vagy kiír valamit a Díjnet (pl. hogy nincs PDF)?

(Jegyzet magamnak: `dijnet-browser.js:97`, hiányzik a content-disposition header. Tüneti kezelés: skip manually via donefile. Jav ötlet: hiba esetén skip file/bill, prevent marking done.)

**Comment by Merwenus** [comment]
Szia,

Megnéztem, nincs hozzá fájl: ` A számlához jelenleg nem elérhető a PDF formátumú számlakép.`
Sőt megnéztem egy régi dumpot is amit 1 éve csináltam másik progival, ott is hiányzik a hiteles PDF, ott egy "SSGOVU~E" fájlt készített helyette.

Úgyhogy ha jól értem elég lenne ha ignorálja a hiányzó fájlokat, és megy tovább, végén pedig kiírja logba, hogy mely fájlok hiányoztak. (az összes Jóváírásos számlánál hiányzik a hitelesített PDF fájl)

**Comment by juzraai** [comment]
Köszi, erre számítottam. Igyekszem javítani hamarosan. :)

**Comment by Merwenus** [comment]
Köszi, ha tesztelni kell ide jöhet, elméletileg folytatja a maradék 10et ahogy néztem.

**Comment by juzraai** [comment]
Javítottam: https://github.com/juzraai/dijnet-bot/releases/tag/v2.1.6

Mostantól, ha egy fájlt nem tud letölteni, akkor erről tájékoztat, másrészt az adott számlát nem fogja késznek jelölni. Ez azt is jelenti, hogy következő futtatáskor ismét megnézi majd, elérhető-e a fájl a Díjnet-en. (Vannak olyan szolgáltatók, ahol késik a PDF, ezért nem jelölhetem késznek a számlát automatikusan.)

Ez ellen jelenleg azt lehet tenni (ha biztos vagy abban, hogy nem is lesz PDF), hogy a "kesz.txt"-be beilleszted a számla sorszámát. (Erre majd kitalálok valami univerzálisabb megoldást.)

**Comment by Merwenus** [comment]
Köszi, így folytatja és maradék 10ből letölt 9et, viszont így abszolút nem tölt le semmit a Jóváírásból.
4 fájlt akar letölteni, ebből csak 1-et nem tud, a másik 3 az elérhető az oldalon és letölthető, de így skippeli az egészet (maradék 3at), és soha nem fogja letölteni a Jóváírásokat (egyiket sem, senkinek), mert egyiknél se elérhető a hiteles számla. Jóváírásoknál a hiteles számla ahogy nézem hiányzik, 4-et találtam az elmúlt pár évben lementve, is a hiteles hiányzik, de 3 fájl ott van mindegyiknél.

**Comment by Merwenus** [comment]
Köszi, letöltötte maradékot is! (rossz mappát néztem, az előző letöltés backupját)

**Comment by juzraai** [comment]
Szuper, köszi a visszajelzést! :)
